
oauth:
    client:
        id: client_id
# client_secret required only when Token Endpoint Authentication is enabled on AS
        secret: client_secret
    scope: [openid]
    device_endpoint: https://provider.com/devicecode
    token_endpoint: https://provider.com/token
    userinfo_endpoint: https://provider.com/userinfo

qr:
    before_line: ""
    after_line: ""
    big: false
    inverse: false

texts:
    prompt: |
        Authenticate at
        -----------------
        {url}
        -----------------
        With code: {code}
        -----------------
        {qr}
        Hit enter when you authenticate

users:
    provider_user_sub_1:
      - root
      - bob
    provider_user_sub_2:
      - mike
