
oauth:
    client:
        id: client_id
        secret: client_secret
    scope: [openid, profile, email]
    device_endpoint: https://provider.com/devicecode
    token_endpoint: https://provider.com/token
    userinfo_endpoint: https://provider.com/userinfo

qr:
    before_line: ""
    after_line: ""
    big: false
    inverse: false

texts:
    prompt: |
        Authenticate at
        -----------------
        {url}
        -----------------
        With code: {code}
        -----------------
        {qr}
        Hit enter when you authenticate

users:
    provider_user_sub_1:
      - machine_username_1
      - machine_username_2
    provider_user_sub_2:
      - machine_username_1
      - machine_username_3
